### ISSUE TITLE
 TypeError: 'JavaPackage' object is not callable when running pydeequ

### ISSUE THREAD

**Issue by NastasiaSaby** [awslabs/python-deequ#1]
**Describe the bug**
I've got an exception when I try to run pydeequ: "TypeError: 'JavaPackage' object is not callable".

**To Reproduce**
1. pip install pydeequ==0.1.5
2. Code: 

```
from pyspark.sql import SparkSession, Row
import pydeequ

spark = (SparkSession
    .builder
    .config("spark.jars.packages", pydeequ.deequ_maven_coord)
    .config("spark.jars.excludes", pydeequ.f2j_maven_coord)
    .getOrCreate())

df = spark.sparkContext.parallelize([
            Row(a="foo", b=1, c=5),
            Row(a="bar", b=2, c=6),
            Row(a="baz", b=3, c=None)]).toDF()

from pydeequ.analyzers import *

analysisResult = AnalysisRunner(spark) \
                    .onData(df) \
                    .addAnalyzer(Size()) \
                    .addAnalyzer(Completeness("b")) \
                    .run()
                    
analysisResult_df = AnalyzerContext.successMetricsAsDataFrame(spark, analysisResult)
analysisResult_df.show()
```

3. Execute the code above
4. See error: 
TypeError: 'JavaPackage' object is not callable

**Expected behavior**
I was expecting the results of the analyzer.

**Screenshots**
![image](https://user-images.githubusercontent.com/8245071/99265752-55e4f700-2822-11eb-80a9-0e13d58f2c62.png)

**Desktop (please complete the following information):**
- Apache Spark 3.0.0
- Scala 2.12
- Pydeequ = 0.1.5

**Additional context**
I'm running it on a Databricks cluster.

Thank you for your help.

**Comment by cghyzel** [comment]
@NastasiaSaby The problem that jumps out at me is that you are using Spark 3.0, which we don't support yet. The latest Spark version we support is 2.4.7. 

We can't support Spark 3.0 until Deequ compiles to Scala 2.12 (which is required for Spark 3.0). This is an issue with Deequ as well. Notably, this person opening [this issue](https://github.com/awslabs/deequ/issues/310) had the same error as you.

**Comment by NastasiaSaby** [comment]
Thank you for your answer. I downgraded my cluster to Spark 2.4.5, Scala 2.11. Unfortunately, I'm still getting the error with this new stack trace:

```
TypeError                                 Traceback (most recent call last)
<command-726420478794624> in <module>
      1 from pydeequ.profiles import *
      2 
----> 3 result = ColumnProfilerRunner(spark) \
      4     .onData(df) \
      5     .run()

/local_disk0/.ephemeral_nfs/envs/pythonEnv-3b335b2c-7675-473f-9bce-da0935f38d85/lib/python3.7/site-packages/pydeequ/profiles.py in __init__(self, spark_session)
     27         self._sc = spark_session.sparkContext
     28         self._jvm = spark_session._jvm
---> 29         self._ColumnProfilerRunner = self._jvm.com.amazon.deequ.profiles.ColumnProfilerRunner()
     30 
     31     def onData(self, df):

```

**Comment by NastasiaSaby** [comment]
I'm using the Databricks platform. Is there a known limitation?

**Comment by Mimetis** [comment]
I get the same issue

**Comment by NastasiaSaby** [comment]
This is not linked to pyspark=3.0.1. I've got the issue with Spark 2.4.5 Scala 2.11.

**Comment by gucciwang** [comment]
We have not tested with databricks yet, but here is how you'd get started with an Amazon EMR cluster -- I presume there may be some overlap here! Copy and pasted below: 

Your EMR cluster must be running Spark v2.4.6 in order to work with PyDeequ. Once you have a running cluster that has those components and a SageMaker notebook with the necessary permissions, you can configure a SparkSession object from the below template to connect to your cluster. If you need a refresher on how to connect a SageMaker Notebook to EMR, check out this [AWS blogpost on using Sparkmagic](https://aws.amazon.com/blogs/big-data/submitting-user-applications-with-spark-submit/).

Once you’re in the SageMaker Notebook, run the following JSON in a cell before you start your SparkSession to configure your EMR cluster.

```
%%configure -f
{ "conf":{
          "spark.pyspark.python": "python3",
          "spark.pyspark.virtualenv.enabled": "true",
          "spark.pyspark.virtualenv.type":"native",
          "spark.pyspark.virtualenv.bin.path":"/usr/bin/virtualenv",
          "spark.jars.packages": "com.amazon.deequ:deequ:1.0.3",
          "spark.jars.excludes": "net.sourceforge.f2j:arpack_combined_all"
         }
}
```
Start your SparkSession object in a cell after the above configuration by running `spark`, then use the SparkContext (default named `sc`) to install PyDeequ onto your cluster like so
```
sc.install_pypi_package('pydeequ')
```

**Comment by bballamudi** [comment]
I'm trying to run the example from the tutorials folder from my local machine. I'm getting the same error as the OP.

Spark Version: 2.4.7
pydeequ==0.1.5

Please look at the image attached below

![image](https://user-images.githubusercontent.com/21183667/100185865-807e2200-2eaa-11eb-85c0-f80847f6e6a4.png)

**Comment by MOHACGCG** [comment]
same issue on spark version 2.4.3.
I'm using 2.4.3 hoping to load pydeequ to glue etl. Do you know if deequ is compatible with glue v2?

**Comment by MOHACGCG** [comment]
> same issue on spark version 2.4.3.
> I'm using 2.4.3 hoping to load pydeequ to glue etl. Do you know if deequ is compatible with glue v2?

using `pyspark --jars {PATH_TO_DEEQ_JAR}` resolves this error for me, i think this should be added to the installation steps.

**Comment by bballamudi** [comment]
@MOHACGCG I'm trying to find the path to deequ jar so as to try your solution. I'm looking under the virtual env path: /lib/Python3.7/site-packages/pyspark/jars.
However, I don't see any jar corresponding to deequ in there. So I'm considering downloading and copyting deequ jar under this path to be followed by your command referring to this location. 
Do you think there is a better alternative to this?

**Comment by bballamudi** [comment]
@MOHACGCG The earlier attempt did not work. Also, I think the fourth statement in the code below should do the trick by default in adding the jar files. Cause 'pydeequ.deequ_maven_coord' evaluates to 'com.amazon.deequ:deequ:1.0.3'. Could you shed some light into this @gucciwang ?

spark = (SparkSession
    .builder
    .config("spark.driver.extraClassPath", classpath)
    .config("spark.jars.packages", pydeequ.deequ_maven_coord)
    .config("spark.jars.excludes", pydeequ.f2j_maven_coord)
    .getOrCreate())

**Comment by MOHACGCG** [comment]
> @MOHACGCG I'm trying to find the path to deequ jar so as to try your solution. I'm looking under the virtual env path: /lib/Python3.7/site-packages/pyspark/jars.
> However, I don't see any jar corresponding to deequ in there. So I'm considering downloading and copyting deequ jar under this path to be followed by your command referring to this location.
> Do you think there is a better alternative to this?

I just downloaded the jar from [here](https://mvnrepository.com/artifact/com.amazon.deequ/deequ/1.0.5) and passed it on.

**Comment by gucciwang** [comment]
@bballamudi, you are correct! 

At the beginning of each of our tutorials, we always start off with the following configuration when setting up our SparkSession. This leverages the maven coordinates of the Deequ jar, and subsequently **excluding** an outdated Fortran jar. By using the configuration we provide, the SparkSession will automatically fetch the jars from maven. 
```
import pydeequ

import sagemaker_pyspark
from pyspark.sql import SparkSession, Row

classpath = ":".join(sagemaker_pyspark.classpath_jars()) # aws-specific jars

spark = (SparkSession
    .builder
    .config("spark.driver.extraClassPath", classpath)
    .config("spark.jars.packages", pydeequ.deequ_maven_coord)
    .config("spark.jars.excludes", pydeequ.f2j_maven_coord)
    .getOrCreate())
```

And if you're wondering why we also ref `sagemaker_pyspark`, it's just so that it allows our SparkSession to read in parquet files from S3. An example of it in action is with the [PyDeequ Analyzers tutorial](https://github.com/awslabs/python-deequ/blob/master/tutorials/analyzers.ipynb)

**Comment by bballamudi** [comment]
Thanks @gucciwang for the insight. However, it was not working automatically as intended. Perhaps it was to do with my setup. I followed @MOHACGCG and it works now. Kindly make note of this in the readme file in the interest of larger audience.

**Comment by SerenaLin2020** [comment]
experiencing the same issue. solved by using `pyspark --jars /path-to-the-jar/deequ-1.0.5.jar`
more info:
python version: 3.7.9
spark version: 2.4.7
scala version: 2.13.4

**Comment by gucciwang** [comment]
@SerenaLin2020 We have not tested PyDeequ with `deequ-1.0.5.jar`, so some functionalities may be impaired. Please try with `deequ-1.0.3.jar` and keep us updated! 😄

**Comment by giznaj** [comment]
> pyspark --jars /path-to-the-jar/deequ-1.0.5.jar

Hi SerenaLin2020 - Where did you put that code in your notebook?  Also, are you using a hosted community edition of Databricks?  Where did you physically put the jar file?  Or how did you find it's location?

**Comment by preshen-goobiah** [comment]
I had the same issue running deequ in a SageMaker PySpark Processing Job. Solved with @MOHACGCG suggestion. 

1.  Download the jar from maven
2. Pass to SageMaker Spark Processing

**Comment by byronmamamoney** [comment]
Hi, is support for Spark version 3.1.1 supported. I'm currently on AWS emr-6.3.0. Running the below command:
import pydeequ
pydeequ.deequ_maven_coord
Returns: 'com.amazon.deequ:deequ:1.1.0_spark-2.4-scala-2.11'

I take this value (string) and add it to my .json config where all the custom spark config is maintained.
Running my application py files I get the same issue as the folks above.
I assume it is due to the support for the version of Spark.

Any timeline to the implementation for this?

Cheers

**Comment by SerenaLin2020** [comment]
> @SerenaLin2020 We have not tested PyDeequ with `deequ-1.0.5.jar`, so some functionalities may be impaired. Please try with `deequ-1.0.3.jar` and keep us updated! 😄

Tested PyDeequ with `deequ-1.0.3.jar` , pretty good with some basic metrics such as min, max, mean, compliance etc. Only found that pyspark scripts runs much slower than scala scripts(same logic and same data volume). Not sure if this is pyspark's issue or it's PyDeequ's issue.

**Comment by vinura** [comment]
@SerenaLin2020 Did you try this on a databricks cluster ?

**Comment by SerenaLin2020** [comment]
> @SerenaLin2020 Did you try this on a databricks cluster ?

No, I only run this on EMR cluster

**Comment by vinura** [comment]
I got it to working with databricks by directly installing the jar to the cluster.

**Comment by anusha610** [comment]
> I got it to working with databricks by directly installing the jar to the cluster.

Hi Vinura. Could you please let me know how did you do? I want to directly install the jar to the cluster

**Comment by jinyang08** [comment]
@MOHACGCG @preshen-goobiah @bballamudi  Can you explain how did you download the jar from maven? I found myself lost in trying to find the way to add the deequ jar to the jars folder.

**Comment by vinura** [comment]
I installed the following maven package

com.amazon.deequ:deequ:1.1.0_spark-3.0-scala-2.12

you need to check wthr they have an exact match for your cluster and add it as a maven package on the databricks cluster. @anusha610 if you are running it on locally use the spark object as follows,

spark = (SparkSession
         .builder
         .config("spark.jars.packages", 'com.amazon.deequ:deequ:1.1.0_spark-3.0-scala-2.12')
         .config("spark.jars.excludes", pydeequ.f2j_maven_coord)
         .getOrCreate())

**Comment by alokpotadar** [comment]
> I installed the following maven package directly instead of pydeequ.deequ_maven_coord
> 
> com.amazon.deequ:deequ:1.1.0_spark-3.0-scala-2.12
> 
> you need to check wthr they have an exact match for your cluster and add it as a maven package on the databricks cluster. @anusha610 if you are running it on locally(using dbconnect) use the spark object as follows,
> 
> spark = (SparkSession .builder .config("spark.jars.packages", 'com.amazon.deequ:deequ:1.1.0_spark-3.0-scala-2.12') .config("spark.jars.excludes", pydeequ.f2j_maven_coord) .getOrCreate())

Hi @vinura , I'm still getting the exact same error even after using your method. Please help. I use Spark 3.0.1 and Scala 2.12

**Comment by gbalachandra-takeda** [comment]
@MOHACGCG  @vinura  - Could you please suggest the script changes for this fix?

**Issue**: Am facing the similar error using DataBricks with below pydeequ version
**Error**:  TypeError: 'JavaPackage' object is not callable
```
python version: 3.7.9
pyspark - 2.4.0
scala version: 2.13.4
- **pydeequ-1.0.1** version 
```
**Tried:**
Downloaded the suggested Jars and uploaded to Databricks filestore and passed the same for spark session


```
import pydeequ
import sagemaker_pyspark
from pyspark.sql import SparkSession, Row
classpath = ":".join(sagemaker_pyspark.classpath_jars()) # aws-specific jars
spark = (SparkSession
    .builder
    .config("spark.driver.extraClassPath", classpath)
    .config("spark.jars.packages", '/FileStore/jars/deequ_1_0_5.jar')
    .config("spark.jars.excludes", pydeequ.f2j_maven_coord)
    .getOrCreate())
```
Attached screenshot of error 
<img width="707" alt="deequ_error" src="https://user-images.githubusercontent.com/96808988/152705919-e7711b5b-3a97-4ca1-a43f-16b5dd72fef9.png">

Could you please suggest with appropriate version, steps and scripts for data-bricks implementations

**Comment by admin-excior** [comment]
If anyone struggles with this. I found this worked for me:
1. Download the deequ jar corresponding to the correct spark version
2. In your spark-defaults.conf file add the path of your jar file your downloaded in step1 to the lines below
3. spark.driver.extraClassPath, spark.executor.extraClassPath

**Comment by mikelevvra** [comment]
> Thanks @gucciwang for the insight. However, it was not working automatically as intended. Perhaps it was to do with my setup. I therefore followed @MOHACGCG instruction in the above comment and it works now. Kindly make note of this in the readme file in the interest of larger audience.

Hello, how did you solve it?

I am running spark in a hadoop cluster, with the following config:

Spark 2.4.4
Scala 2.11.12
And I am creating the spark session like this:

spark = (SparkSession
.builder
.appName("PyDeeQu") \
.config("spark.jars", "PATH_TO/deequ-1.1.0_spark-2.4-scala-2.11.jar") \
.config("spark.jars.packages", pydeequ.deequ_maven_coord)\
.config("spark.jars.excludes", pydeequ.f2j_maven_coord)\
.config("spark.sql.execution.arrow.enabled", "true")\
.config("spark.sql.sources.partitionOverwriteMode","dynamic")\
.getOrCreate())


I keep getting this error: TypeError: 'JavaPackage' object is not callable, and I don't know why...

**Comment by vinura** [comment]
It works fine with following configuration,

Use https://mvnrepository.com/artifact/com.amazon.deequ/deequ 
to pick the deeque version and spark version for `spark.jars.package`

```
from pyspark.sql import SparkSession, DataFrame
import pydeequ


def create_spark():
    """Function to get Spark Configuration"""
    spark = (
        SparkSession.builder.config(
            "spark.jars.packages", "com.amazon.deequ:deequ:2.0.1-spark-3.2"
        )
        .config("spark.jars.excludes", pydeequ.f2j_maven_coord)
        .getOrCreate()
    )
    return spark
```

**Comment by Bhavanabuddy** [comment]
@vinura , i followed above one . However i have to add two lines of code to state Spark version in "Azure databricks"

from pyspark.sql import SparkSession, DataFrame
import os
os.environ['SPARK_VERSION'] = '3.2'
import pydeequ

   
spark = SparkSession.builder.config("spark.jars.packages", "com.amazon.deequ:deequ:2.0.1-spark-3.2").config("spark.jars.excludes", pydeequ.f2j_maven_coord).getOrCreate()
==================================

# The below spark session worked for 3.2 

from pyspark.sql import SparkSession, DataFrame
import os
os.environ['SPARK_VERSION'] = '3.2'
import pydeequ

spark2 = SparkSession.builder.appName('xyz').getOrCreate()

**Comment by vinura** [comment]
@Bhavanabuddy I added the spark version when using databricks connect (IDE/pyCharm) but not when using databricks notebooks.

Either way, I hope this fixes all the problems.

**Comment by sham-hq** [comment]
It troubled me for 2 days as well on EMR. Configuration I was trying: 
emr-7.2.0, 
pyspark: 3.5.1, 
Deequ: 1.4.0
When I was using below code, I was continuously getting `TypeError: 'JavaPackage' object` error
```
spark = SparkSession.builder.appName("TestDQ") \
    .config("spark.jars.packages", pydeequ.deequ_maven_coord) \
    .config("spark.jars.excludes", pydeequ.f2j_maven_coord) \
    .config("spark.sql.parquet.int96RebaseModeInRead", "CORRECTED") \
    .getOrCreate()

```

**Solution worked for me:**
1. Installed `pydeequ==1.4.0` using bootstrap script
2. pass `com.amazon.deequ:deequ:2.0.8-spark-3.5` while spark-submit. e.g. `spark-submit --packages com.amazon.deequ:deequ:2.0.8-spark-3.5`
3. while initializing spark, used below code:
```
spark = SparkSession.builder.appName("TestDQ") \
    .config("spark.jars.excludes", pydeequ.f2j_maven_coord) \
    .config("spark.sql.parquet.int96RebaseModeInRead", "CORRECTED") \
    .getOrCreate()
```
Thanks

**Comment by parasupadhyay** [comment]
> I was able to combine some of the above solutions and other solutions and get pydeeque working on Azure Databricks in a notebook. Here are the details, if helpful for anyone.
> 
> From [this link](https://mvnrepository.com/artifact/com.amazon.deequ/deequ), I downloaded the appropriate JAR file to match my Spark version. In my case, that was `deequ_2_0_1_spark_3_2.jar`. I then installed this file using the JAR type under Libraries in my cluster configurations.
> 
> The following then worked, ran in different cells.
> 
> ```
> %pip install pydeequ
> ```
> 
> ```
> %sh export SPARK_VERSION=3.2.1
> ```
> 
> ```
> df = spark.read.load("abfss://container-name@account.dfs.core.windows.net/path/to/data")
> ```
> 
> ```
> from pyspark.sql import SparkSession
> 
> import pydeequ
> 
> spark = (SparkSession
>     .builder
>     .getOrCreate())
> ```
> 
> ```
> from pydeequ.analyzers import *
> 
> analysisResult = AnalysisRunner(spark) \
>                     .onData(df) \
>                     .addAnalyzer(Size()) \
>                     .addAnalyzer(Completeness("b")) \
>                     .run()
> 
> analysisResult_df = AnalyzerContext.successMetricsAsDataFrame(spark, analysisResult)
> analysisResult_df.show()
> ```
> ```

**Comment by parasupadhyay** [comment]
> I was able to combine some of the above solutions and other solutions and get pydeeque working on Azure Databricks in a notebook. Here are the details, if helpful for anyone.
> 
> From [this link](https://mvnrepository.com/artifact/com.amazon.deequ/deequ), I downloaded the appropriate JAR file to match my Spark version. In my case, that was `deequ_2_0_1_spark_3_2.jar`. I then installed this file using the JAR type under Libraries in my cluster configurations.
> 
> The following then worked, ran in different cells.
> 
> ```
> %pip install pydeequ
> ```
> 
> ```
> %sh export SPARK_VERSION=3.2.1
> ```
> 
> ```
> df = spark.read.load("abfss://container-name@account.dfs.core.windows.net/path/to/data")
> ```
> 
> ```
> from pyspark.sql import SparkSession
> 
> import pydeequ
> 
> spark = (SparkSession
>     .builder
>     .getOrCreate())
> ```
> 
> ```
> from pydeequ.analyzers import *
> 
> analysisResult = AnalysisRunner(spark) \
>                     .onData(df) \
>                     .addAnalyzer(Size()) \
>                     .addAnalyzer(Completeness("b")) \
>                     .run()
> 
> analysisResult_df = AnalyzerContext.successMetricsAsDataFrame(spark, analysisResult)
> analysisResult_df.show()
> ```
> ```

@ethanwicker connected with you on linkinin regarding this. Do you think Unity catalog was enabled in your account during this work?

**Comment by ethanwicker** [comment]
@parasupadhyay Unity Catalog was not enabled at the time I originally posted that solution
