### ISSUE TITLE
Support hasPattern check

### ISSUE THREAD

**Issue by agessner** [awslabs/python-deequ#10]
**Is your feature request related to a problem? Please describe.**

Hey guys! Thanks for the amazing lib! I'm just wondering where the `.hasPattern` method will be available? We are giving the lib a shot, and it would be great to have this feature working.

**Describe the solution you'd like**

Being able to use the .hasPattern method

**Comment by MOHACGCG** [comment]
as a workaround you can use check.satisfies with RLIKE. not as nice but works!

**Comment by agessner** [comment]
Thanks @MOHACGCG, I just got the chance to test it now and I'm having the same issue described here https://github.com/awslabs/python-deequ/issues/18

**Comment by MOHACGCG** [comment]
@agessner satisfies works. see my response on #18.

**Comment by gucciwang** [comment]
@MOHACGCG @agessner Apologies for the late response, but wanted to let you guys know that it's been implemented and shipped with pydeequ==0.1.6! Please give it a try and let me know if there are any issues! 

Example usage can be found here: 
https://github.com/awslabs/python-deequ/blob/master/tutorials/hasPattern_check.ipynb
