### ISSUE TITLE
PyDeequ Stable Release (1.1.0)

### ISSUE THREAD

**Issue by chenliu0831** [awslabs/python-deequ#106]
This is a meta issue to list major enhancement, features and bug-fixes to bring PyDeequ to a stable release. 

Please add a comment with the PRs, issues (create if not exist) or ideas you would like to bring us to stable release. 

More to come..

## Completed Item

- https://github.com/awslabs/python-deequ/pull/100. This closes multiple issues and bring dependency up to date.
- https://github.com/awslabs/python-deequ/pull/120

## Release Plan

- [x] 1.1.0rc0 PR
- [x] 1.1.0rc0 on PYPI
- [x] 1.1.0rc0 baking, asking for feedback. ETA 1-2 week. On-going, ending ETA 06/30
- [x] 1.1.0 PR - https://github.com/awslabs/python-deequ/pull/139
- [x] 1.1.0 on PYPI. ETA: early July or sooner if RC went smooth

**Comment by poolis** [comment]
hasPattern implementation

https://github.com/awslabs/python-deequ/issues/71
https://github.com/awslabs/python-deequ/pull/76

**Comment by SemyonSinchenko** [comment]
Hello! What is expected date of the release?

**Comment by mycaule** [comment]
Yes for example in my company, we are using great expectations instead of PyDeequ for Spark/Python because 1.0 isn't available yet. But otherwise, for Spark/Scala project Deequ looked reasonable for that same company.

**Comment by lecardozo** [comment]
A couple of things I think we should consider before this release:

- Resolve #111, which is breaking the master branch;
- Improve coverage for tests and modernize the test stack;
- Improve CI for PRs (so we can see if tests are running properly before merging)

**Comment by marius-xentral** [comment]
any news here?

**Comment by lhendrick-t10** [comment]
Would really love to see this released!

**Comment by chenliu0831** [comment]
> 

That's unfortunate - we could still release 1.1.0 though, there does not seem to be breaking changes. 

We are working through some administrative issues - expect another update in 2-3 weeks

**Comment by runkelcorey** [comment]
@chenliu0831 following up on your last message. What's happened in the last few weeks?

**Comment by revolutionisme** [comment]
@chenliu0831, is there a timeline on this update? We are looking to use pydeequ with glue 4.0 .

**Comment by chenliu0831** [comment]
We are still blocked on a few administrative (and technical) issues. I have been actively follow-ing up to resolve those. But I do not have ETA at this time.

**Comment by chenliu0831** [comment]
Update - we resolved the issues. Targeting to release to PYPI by end of Jun.

**Comment by chenliu0831** [comment]
Publish 1.1.0rc0 to PYPI - we will bake for about 2 weeks. See notes https://github.com/awslabs/python-deequ/releases/tag/v1.1.0rc0

**Comment by chenliu0831** [comment]
@revolutionisme @runkelcorey @lhendrick-t10 @marius-xentral  @lecardozo, tagging just as an FYI. Install instruction in pre-release note https://github.com/awslabs/python-deequ/releases/tag/v1.1.0rc0. Any feedback is welcome if you get chance to try it out

**Comment by chenliu0831** [comment]
We released to PYPI! 

https://pypi.org/project/pydeequ/
