### ISSUE TITLE
Slack community

### ISSUE THREAD

**Issue by slapekm** [awslabs/python-deequ#121]
Maybe we will create a community on Slack? I saw it was but now the link is not available. 👍🏻

**Comment by haojiliu** [comment]
didn't see this, i made a similar request, would be good to have a community!

**Comment by LiorBroideWix** [comment]
Yup. Would be much appreciated.

**Comment by chenliu0831** [comment]
Let's use Github Issue with `question` tag for now - See https://github.com/awslabs/deequ/issues/450#issuecomment-1450877217
