### ISSUE TITLE
dev slack channel is invalid

### ISSUE THREAD

**Issue by haojiliu** [awslabs/python-deequ#124]
hi, i'm interested in this project and have a few dev related Qs, the slack link seems to be outdated on the home page, can someone share the latest link?

**Comment by markgis** [comment]
I'm starting to wander if this  project is dead? 
There are a lot of on going PRs and issues with no real code push for a while 🤷‍♂️

**Comment by chenliu0831** [comment]
@markgis the project is not dead and is being maintained (see comments here as well https://github.com/awslabs/deequ/issues/450#issuecomment-1447287038) . Expect some ramp up in a few weeks though. 

@haojiliu  let's use Github issues with `question` tag for your questions for now. We will look into other discussion channels. 

Closing.
