### ISSUE TITLE
Pydeequ to support additional where filters

### ISSUE THREAD

**Issue by andreimekk** [awslabs/python-deequ#158]
**Is your feature request related to a problem? Please describe.**
From what I can understand there's no implementation of CheckWithLastConstranitFilterable from Deequ in Pydeequ which makes it impossible to add  (.where) method at the end of the defined check. Is there any particular reason for that or it's just part of Deequ that hasn't been implemented yet?

**Describe the solution you'd like**
Additional class in Pydeequ that extends Check so that we can specify additional SQL WHERE statement to apply before evaluation of the previous constraint.

**Comment by chenliu0831** [comment]
It's not implemented yet - I think this was planned before https://github.com/awslabs/python-deequ/issues/30.

**Comment by chenliu0831** [comment]
Will do a minor version release around EOW 12/08 - 12/11

**Comment by chenliu0831** [comment]
Closing, released in https://github.com/awslabs/python-deequ/releases/tag/v1.2.0
