### ISSUE TITLE
pydeequ2 ??

### ISSUE THREAD

**Issue by dwp0980** [awslabs/python-deequ#191]
https://pypi.org/project/pydeequ2/ vs https://pypi.org/project/pydeequ/ - any idea what's going on there?

**Comment by chenliu0831** [comment]
I don't know about this project and this person is obviously NOT one of the maintainers. The PYPI page seems generated from a direct upload of a very old version of PyDeequ.

Thanks for reporting I will follow-up with our internal team to address this matter.

**Comment by chenliu0831** [comment]
Closing this one. https://pypi.org/project/pydeequ/ is the only official distribution. Do not trust any other repo.
