### ISSUE TITLE
PySpark Error

### ISSUE THREAD

**Issue by archi-2001** [awslabs/python-deequ#194]
**py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: java.lang.IllegalAccessError: class org.apache.spark.storage.StorageUtils$ (in unnamed module @0x65f095f8) cannot access class sun.nio.ch.DirectBuffer (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x65f095f8**

**To Reproduce**
1. Go to VSCode
2. Type:

from pyspark.sql import SparkSession, Row
import pydeequ
spark = (SparkSession
.builder
.config("spark.jars.packages", pydeequ.deequ_maven_coord)
.config("spark.jars.excludes", pydeequ.f2j_maven_coord)
.getOrCreate())
df = spark.sparkContext.parallelize([
Row(a="foo", b=1, c=5),
Row(a="bar", b=2, c=6),
Row(a="baz", b=3, c=None)]).toDF()

4. Run python file
5. See error

**Screenshots**
![image](https://github.com/awslabs/python-deequ/assets/104158849/d54ff1fd-3124-4cf5-8c5d-74d251292336)

**Version information:**
 - OS: Windows 10, 64-bit os
-  Application: vscode
 - Python version: 3.11.7
 - PySpark version: 3.2
 - Hadoop version: 2.7
 - JDK version: 17
 - Environment variables created: SPARK_HOME, HADOOP_HOME, JAVA_HOME, SPARK_VERSION

**Comment by chintanrabadiya** [comment]
how you connect your spark connection? mean using docker or something else. I have same issue which solve after when connect it properly

**Comment by chenliu0831** [comment]
See if this helps https://stackoverflow.com/questions/73465937/apache-spark-3-3-0-breaks-on-java-17-with-cannot-access-class-sun-nio-ch-direct. But otherwise, we don't support Spark setup issues.
