### ISSUE TITLE
Contributing link broken

### ISSUE THREAD

**Issue by asears** [awslabs/python-deequ#3]
**Describe the bug**
On page: 
https://pydeequ.readthedocs.io/en/latest/README.html#repository

This link is incorrect:
https://github.com/awslabs/python-deequ/blob/master/CONTRIBUTING

should be https://github.com/awslabs/python-deequ/blob/master/CONTRIBUTING.md

**Comment by mayankgupta804** [comment]
this issue has been resolved.
