### ISSUE TITLE
List of constraints support feature is not available in pydeequ 0.1.8

### ISSUE THREAD

**Issue by Sankeernalk** [awslabs/python-deequ#59]
This feature is not available in pydeequ 0.1.8

_Originally posted by @Sankeernalk in https://github.com/awslabs/python-deequ/issues/39#issuecomment-884684651_

**Comment by gucciwang** [comment]
So sorry about that! Hotfix coming soon :)

**Comment by gucciwang** [comment]
Fixed with version 1.0.0!
