### ISSUE TITLE
Create an example for anomaly detection

### ISSUE THREAD

**Issue by Sankeernalk** [awslabs/python-deequ#61]
Please create an example for Holtwinters anomaly detection algo usage in pydeequ

**Comment by jaoanan1126** [comment]
Hi @Sankeernalk, here's a [blogpost](https://aws.amazon.com/blogs/big-data/monitor-data-quality-in-your-data-lake-using-pydeequ-and-aws-glue/) that leverages Holt Winters in PyDeequ and the [documentation](https://pydeequ.readthedocs.io/en/latest/pydeequ.html?highlight=Holt%20Winters#pydeequ.anomaly_detection.HoltWinters). Let me know if that helps!

**Comment by Sankeernalk** [comment]
Thanks @jaoanan1126 I shall check
