### ISSUE TITLE
hasPattern check is no longer implemented in 0.1.8 (was available in 0.1.7)

### ISSUE THREAD

**Issue by poolis** [awslabs/python-deequ#71]
`pydeequ.checks.Check.hasPattern` is no longer implemented (method is a no-op):

https://github.com/awslabs/python-deequ/blob/2449f6058548c19300c42c2451a64a2e1af73aa3/pydeequ/checks.py#L555

In tag` 0.1.7` it was implemented as expected:
https://github.com/awslabs/python-deequ/blob/2ee4f70adc009cb264066ce41ee9b610113e1a8f/pydeequ/checks.py#L551

Was it removed for some reason?   I realize you can use `satisfies` to work around the issue but hasPattern is more user friendly.  I have no problem creating a PR for the change, just want to make sure there wasn't some particular reason it was removed before spending any time on it.  Thanks!

**Comment by chenliu0831** [comment]
I just merged https://github.com/awslabs/python-deequ/pull/66 which should address this

**Comment by chenliu0831** [comment]
Tracking in https://github.com/awslabs/python-deequ/issues/152.
