### ISSUE TITLE
Unable to compute Uniqueness/UniqueValueRatio

### ISSUE THREAD

**Issue by ol-eg** [awslabs/python-deequ#8]
**Describe the bug**
Trying the lib on jupyter notebook, the example from quickstart. When trying to compute Uniqueness or UniqueValueRation facing java exception  'Method iterableAsScalaIterable([class java.lang.String]) does not exist'

**To Reproduce**
Steps to reproduce the behaviour:
1. start jupyter notebook in docker, one of the latest images from jupyter team:
```$ docker run -p 8888:8888 jupyter/all-spark-notebook:a0a544e6dc6e```
2. Install pydeequ from inside jupyter notebook
```!pip install pydeequ```
3. Follow the quickstart instructions to set up spark session and run deequ analysers. At this point everything works, however adding analyser .addAnalyzer(Uniqueness("b"))  Brings the error. (screenshots attached).

**Screenshots**
![image](https://user-images.githubusercontent.com/22866225/102978790-1e9af180-4516-11eb-9b05-61a178d04325.png)
![image](https://user-images.githubusercontent.com/22866225/102978859-40947400-4516-11eb-95c1-328f9ee06af7.png)
![image](https://user-images.githubusercontent.com/22866225/102979121-aaad1900-4516-11eb-8e44-4c47af3cd40e.png)
![image](https://user-images.githubusercontent.com/22866225/102979503-332bb980-4517-11eb-8b89-2a9dc17ac07e.png)

**Additional context**
I have tried few different combinations of spark/scala/amazon deequ libs versions but did not manage to make this work.

**Comment by gucciwang** [comment]
Hi! Apologies for the late reply amidst the holidays, but my guess is that your spark session is unable to access the  `deequ-1.0.3.jar`. We leverage `ivy` to download the jar from maven, so perhaps there is a disconnect of where those jars are stored between docker and your main machine. From the looks of the screenshot, you listed your jars in `/usr/local/spark/jars/` whereas ivy downloaded `deequ-1.0.3.jar` into `/home/jovyan/.ivy2/jars/`. 

Does your notebook work with just running the `addAnalyzer(Size())`? That would reinforce the fact that the sparksession is unable to access the deequ jar. 

Also, we have only developed and supported up to `deequ-1.0.3`, so please stick to that version!

**Comment by ol-eg** [comment]
Hi, thx for coming back. That is I thinks the issue:
![image](https://user-images.githubusercontent.com/22866225/104027724-d8fa4c00-51d8-11eb-9069-d537d40d51a0.png)

I think for me the fix will be to find the image with compatible spark/scala versions, and configure pyspark with extra ivy2 path.

thx vm.
