### ISSUE TITLE
"hasPattern" method code is missing in "Check" Class

### ISSUE THREAD

**Issue by Reydaa** [awslabs/python-deequ#87]
Checking pattern tutorial (Notebook : tutorials/hasPattern_check.ipynb) does not work. The code for 'hasPattern' method is missing, calling it results in a 'NoneType' .

![image](https://user-images.githubusercontent.com/62269958/143785825-0a7bf6f5-b4dd-4b52-9a35-ac5b6ecd0339.png)

Thank you in advance !

**Comment by poolis** [comment]
This PR might address this... https://github.com/awslabs/python-deequ/pull/76

**Comment by alanstos** [comment]
+1

**Comment by idanyliuk** [comment]
+1

**Comment by TomKilleenTR** [comment]
any updates on this ?  I'm receiving the same error.

**Comment by chenliu0831** [comment]
I just merged https://github.com/awslabs/python-deequ/pull/66 which should address this.

**Comment by chenliu0831** [comment]
Closing in favor of https://github.com/awslabs/python-deequ/issues/152
